default:	cpsc2150/extendedConnectX/GameBoard/GameScreen.java cpsc2150/extendedConnectX/GameBoard/GameBoard.java cpsc2150/extendedConnectX/GameBoard/AbsGameBoard.java cpsc2150/extendedConnectX/GameBoard/BoardPosition.java cpsc2150/extendedConnectX/GameBoard/GameBoardMem.java
	javac cpsc2150/extendedConnectX/GameBoard/GameScreen.java cpsc2150/extendedConnectX/GameBoard/GameBoard.java cpsc2150/extendedConnectX/GameBoard/AbsGameBoard.java cpsc2150/extendedConnectX/GameBoard/BoardPosition.java cpsc2150/extendedConnectX/GameBoard/GameBoardMem.java

run:	cpsc2150/extendedConnectX/GameBoard/GameScreen.java cpsc2150/extendedConnectX/GameBoard/GameBoard.java cpsc2150/extendedConnectX/GameBoard/AbsGameBoard.java cpsc2150/extendedConnectX/GameBoard/BoardPosition.java cpsc2150/extendedConnectX/GameBoard/GameBoardMem.java
	java GameScreen

clean:
	rm -f cpsc2150/extendedConnectX/GameBoard/*.class

